----------- Warning, this file is autogenerated by cbindgen. Don't modify this manually. -----------
local ffi = require("ffi")
ffi.cdef[[




typedef struct C_AudioBuffer {
  double *ptr;
  size_t len;
  size_t cap;
} C_AudioBuffer;

void add(void *stream_ptr);

void block_free(struct C_AudioBuffer block);

void pause(void *stream_ptr);

void play(void *stream_ptr);

struct C_AudioBuffer render_block(void *stream_ptr);

bool rx_is_empty(void *stream_ptr);

float rx_pop(void *stream_ptr);

void send_CV(void *stream_ptr, size_t ch, float freq, float vol);

void stream_free(void *stream_ptr);

void *stream_new(const char *host_ptr, const char *device_ptr);

]]
