local ui = {}

ui.RESIZE_W = 5
ui.MIN_SIZE = 32
ui.HEADER = 32
ui.BORDER_RADIUS = 4
ui.BORDER_SIZE = 1
ui.RIBBON = 32

ui.GRID = 28
ui.SLIDER_HEIGHT = 18
ui.SLIDER_RADIUS = 6
ui.SLIDER_TEXT_PAD = 150
ui.SLIDER_OFFSET = 8
ui.BUTTON_SMALL = 18

return ui
