use winit::keyboard::KeyCode;

/// Converts a KeyCode to its Love2D KeyConstant string representation.
/// Returns None for keys that don't have a Love2D equivalent.
pub fn keycode_to_love2d_key(keycode: KeyCode) -> Option<&'static str> {
    match keycode {
        // Character keys (lowercase a-z)
        KeyCode::KeyA => Some("a"),
        KeyCode::KeyB => Some("b"),
        KeyCode::KeyC => Some("c"),
        KeyCode::KeyD => Some("d"),
        KeyCode::KeyE => Some("e"),
        KeyCode::KeyF => Some("f"),
        KeyCode::KeyG => Some("g"),
        KeyCode::KeyH => Some("h"),
        KeyCode::KeyI => Some("i"),
        KeyCode::KeyJ => Some("j"),
        KeyCode::KeyK => Some("k"),
        KeyCode::KeyL => Some("l"),
        KeyCode::KeyM => Some("m"),
        KeyCode::KeyN => Some("n"),
        KeyCode::KeyO => Some("o"),
        KeyCode::KeyP => Some("p"),
        KeyCode::KeyQ => Some("q"),
        KeyCode::KeyR => Some("r"),
        KeyCode::KeyS => Some("s"),
        KeyCode::KeyT => Some("t"),
        KeyCode::KeyU => Some("u"),
        KeyCode::KeyV => Some("v"),
        KeyCode::KeyW => Some("w"),
        KeyCode::KeyX => Some("x"),
        KeyCode::KeyY => Some("y"),
        KeyCode::KeyZ => Some("z"),

        // Number keys
        KeyCode::Digit0 => Some("0"),
        KeyCode::Digit1 => Some("1"),
        KeyCode::Digit2 => Some("2"),
        KeyCode::Digit3 => Some("3"),
        KeyCode::Digit4 => Some("4"),
        KeyCode::Digit5 => Some("5"),
        KeyCode::Digit6 => Some("6"),
        KeyCode::Digit7 => Some("7"),
        KeyCode::Digit8 => Some("8"),
        KeyCode::Digit9 => Some("9"),

        // Punctuation and symbols
        KeyCode::Space => Some("space"),
        KeyCode::Comma => Some(","),
        KeyCode::Minus => Some("-"),
        KeyCode::Period => Some("."),
        KeyCode::Slash => Some("/"),
        KeyCode::Semicolon => Some(";"),
        KeyCode::Equal => Some("="),
        KeyCode::BracketLeft => Some("["),
        KeyCode::Backslash => Some("\\"),
        KeyCode::BracketRight => Some("]"),
        KeyCode::Backquote => Some("`"),
        KeyCode::Quote => Some("'"),

        // Numpad keys
        KeyCode::Numpad0 => Some("kp0"),
        KeyCode::Numpad1 => Some("kp1"),
        KeyCode::Numpad2 => Some("kp2"),
        KeyCode::Numpad3 => Some("kp3"),
        KeyCode::Numpad4 => Some("kp4"),
        KeyCode::Numpad5 => Some("kp5"),
        KeyCode::Numpad6 => Some("kp6"),
        KeyCode::Numpad7 => Some("kp7"),
        KeyCode::Numpad8 => Some("kp8"),
        KeyCode::Numpad9 => Some("kp9"),
        KeyCode::NumpadDecimal => Some("kp."),
        KeyCode::NumpadComma => Some("kp,"),
        KeyCode::NumpadDivide => Some("kp/"),
        KeyCode::NumpadMultiply => Some("kp*"),
        KeyCode::NumpadSubtract => Some("kp-"),
        KeyCode::NumpadAdd => Some("kp+"),
        KeyCode::NumpadEnter => Some("kpenter"),
        KeyCode::NumpadEqual => Some("kp="),

        // Navigation keys
        KeyCode::ArrowUp => Some("up"),
        KeyCode::ArrowDown => Some("down"),
        KeyCode::ArrowRight => Some("right"),
        KeyCode::ArrowLeft => Some("left"),
        KeyCode::Home => Some("home"),
        KeyCode::End => Some("end"),
        KeyCode::PageUp => Some("pageup"),
        KeyCode::PageDown => Some("pagedown"),

        // Editing keys
        KeyCode::Insert => Some("insert"),
        KeyCode::Backspace => Some("backspace"),
        KeyCode::Tab => Some("tab"),
        KeyCode::NumpadClear => Some("clear"),
        KeyCode::Enter => Some("return"),
        KeyCode::Delete => Some("delete"),

        // Function keys
        KeyCode::F1 => Some("f1"),
        KeyCode::F2 => Some("f2"),
        KeyCode::F3 => Some("f3"),
        KeyCode::F4 => Some("f4"),
        KeyCode::F5 => Some("f5"),
        KeyCode::F6 => Some("f6"),
        KeyCode::F7 => Some("f7"),
        KeyCode::F8 => Some("f8"),
        KeyCode::F9 => Some("f9"),
        KeyCode::F10 => Some("f10"),
        KeyCode::F11 => Some("f11"),
        KeyCode::F12 => Some("f12"),
        KeyCode::F13 => Some("f13"),
        KeyCode::F14 => Some("f14"),
        KeyCode::F15 => Some("f15"),
        KeyCode::F16 => Some("f16"),
        KeyCode::F17 => Some("f17"),
        KeyCode::F18 => Some("f18"),
        // F19-F35 are not in Love2D spec

        // Modifier keys
        KeyCode::NumLock => Some("numlock"),
        KeyCode::CapsLock => Some("capslock"),
        KeyCode::ScrollLock => Some("scrolllock"),
        KeyCode::ShiftRight => Some("rshift"),
        KeyCode::ShiftLeft => Some("lshift"),
        KeyCode::ControlRight => Some("rctrl"),
        KeyCode::ControlLeft => Some("lctrl"),
        KeyCode::AltRight => Some("ralt"),
        KeyCode::AltLeft => Some("lalt"),
        KeyCode::SuperRight => Some("rgui"),
        KeyCode::SuperLeft => Some("lgui"),
        // KeyCode::Mode would be "mode" but it's not in included

        // Application keys
        KeyCode::BrowserSearch => Some("appsearch"),
        KeyCode::BrowserHome => Some("apphome"),
        KeyCode::BrowserBack => Some("appback"),
        KeyCode::BrowserForward => Some("appforward"),
        KeyCode::BrowserRefresh => Some("apprefresh"),
        KeyCode::BrowserFavorites => Some("appbookmarks"),

        // Miscellaneous keys
        KeyCode::Pause => Some("pause"),
        KeyCode::Escape => Some("escape"),
        KeyCode::Help => Some("help"),
        KeyCode::PrintScreen => Some("printscreen"),
        // KeyCode::SysReq would be "sysreq" but it's not in included
        KeyCode::ContextMenu => Some("application"),
        KeyCode::Power => Some("power"),
        KeyCode::Undo => Some("undo"),

        _ => None,
    }
}

pub fn love2d_key_to_keycode(key: &str) -> Option<KeyCode> {
    match key {
        // Character keys (lowercase a-z)
        "a" => Some(KeyCode::KeyA),
        "b" => Some(KeyCode::KeyB),
        "c" => Some(KeyCode::KeyC),
        "d" => Some(KeyCode::KeyD),
        "e" => Some(KeyCode::KeyE),
        "f" => Some(KeyCode::KeyF),
        "g" => Some(KeyCode::KeyG),
        "h" => Some(KeyCode::KeyH),
        "i" => Some(KeyCode::KeyI),
        "j" => Some(KeyCode::KeyJ),
        "k" => Some(KeyCode::KeyK),
        "l" => Some(KeyCode::KeyL),
        "m" => Some(KeyCode::KeyM),
        "n" => Some(KeyCode::KeyN),
        "o" => Some(KeyCode::KeyO),
        "p" => Some(KeyCode::KeyP),
        "q" => Some(KeyCode::KeyQ),
        "r" => Some(KeyCode::KeyR),
        "s" => Some(KeyCode::KeyS),
        "t" => Some(KeyCode::KeyT),
        "u" => Some(KeyCode::KeyU),
        "v" => Some(KeyCode::KeyV),
        "w" => Some(KeyCode::KeyW),
        "x" => Some(KeyCode::KeyX),
        "y" => Some(KeyCode::KeyY),
        "z" => Some(KeyCode::KeyZ),

        // Number keys
        "0" => Some(KeyCode::Digit0),
        "1" => Some(KeyCode::Digit1),
        "2" => Some(KeyCode::Digit2),
        "3" => Some(KeyCode::Digit3),
        "4" => Some(KeyCode::Digit4),
        "5" => Some(KeyCode::Digit5),
        "6" => Some(KeyCode::Digit6),
        "7" => Some(KeyCode::Digit7),
        "8" => Some(KeyCode::Digit8),
        "9" => Some(KeyCode::Digit9),

        // Punctuation and symbols
        "space" => Some(KeyCode::Space),
        "," => Some(KeyCode::Comma),
        "-" => Some(KeyCode::Minus),
        "." => Some(KeyCode::Period),
        "/" => Some(KeyCode::Slash),
        ";" => Some(KeyCode::Semicolon),
        "=" => Some(KeyCode::Equal),
        "[" => Some(KeyCode::BracketLeft),
        "\\" => Some(KeyCode::Backslash),
        "]" => Some(KeyCode::BracketRight),
        "`" => Some(KeyCode::Backquote),
        "'" => Some(KeyCode::Quote),

        // Numpad keys
        "kp0" => Some(KeyCode::Numpad0),
        "kp1" => Some(KeyCode::Numpad1),
        "kp2" => Some(KeyCode::Numpad2),
        "kp3" => Some(KeyCode::Numpad3),
        "kp4" => Some(KeyCode::Numpad4),
        "kp5" => Some(KeyCode::Numpad5),
        "kp6" => Some(KeyCode::Numpad6),
        "kp7" => Some(KeyCode::Numpad7),
        "kp8" => Some(KeyCode::Numpad8),
        "kp9" => Some(KeyCode::Numpad9),
        "kp." => Some(KeyCode::NumpadDecimal),
        "kp," => Some(KeyCode::NumpadComma),
        "kp/" => Some(KeyCode::NumpadDivide),
        "kp*" => Some(KeyCode::NumpadMultiply),
        "kp-" => Some(KeyCode::NumpadSubtract),
        "kp+" => Some(KeyCode::NumpadAdd),
        "kpenter" => Some(KeyCode::NumpadEnter),
        "kp=" => Some(KeyCode::NumpadEqual),

        // Navigation keys
        "up" => Some(KeyCode::ArrowUp),
        "down" => Some(KeyCode::ArrowDown),
        "right" => Some(KeyCode::ArrowRight),
        "left" => Some(KeyCode::ArrowLeft),
        "home" => Some(KeyCode::Home),
        "end" => Some(KeyCode::End),
        "pageup" => Some(KeyCode::PageUp),
        "pagedown" => Some(KeyCode::PageDown),

        // Editing keys
        "insert" => Some(KeyCode::Insert),
        "backspace" => Some(KeyCode::Backspace),
        "tab" => Some(KeyCode::Tab),
        "clear" => Some(KeyCode::NumpadClear),
        "return" => Some(KeyCode::Enter),
        "delete" => Some(KeyCode::Delete),

        // Function keys
        "f1" => Some(KeyCode::F1),
        "f2" => Some(KeyCode::F2),
        "f3" => Some(KeyCode::F3),
        "f4" => Some(KeyCode::F4),
        "f5" => Some(KeyCode::F5),
        "f6" => Some(KeyCode::F6),
        "f7" => Some(KeyCode::F7),
        "f8" => Some(KeyCode::F8),
        "f9" => Some(KeyCode::F9),
        "f10" => Some(KeyCode::F10),
        "f11" => Some(KeyCode::F11),
        "f12" => Some(KeyCode::F12),
        "f13" => Some(KeyCode::F13),
        "f14" => Some(KeyCode::F14),
        "f15" => Some(KeyCode::F15),
        "f16" => Some(KeyCode::F16),
        "f17" => Some(KeyCode::F17),
        "f18" => Some(KeyCode::F18),

        // Modifier keys
        "numlock" => Some(KeyCode::NumLock),
        "capslock" => Some(KeyCode::CapsLock),
        "scrolllock" => Some(KeyCode::ScrollLock),
        "rshift" => Some(KeyCode::ShiftRight),
        "lshift" => Some(KeyCode::ShiftLeft),
        "rctrl" => Some(KeyCode::ControlRight),
        "lctrl" => Some(KeyCode::ControlLeft),
        "ralt" => Some(KeyCode::AltRight),
        "lalt" => Some(KeyCode::AltLeft),
        "rgui" => Some(KeyCode::SuperRight),
        "lgui" => Some(KeyCode::SuperLeft),

        // Application keys
        "appsearch" => Some(KeyCode::BrowserSearch),
        "apphome" => Some(KeyCode::BrowserHome),
        "appback" => Some(KeyCode::BrowserBack),
        "appforward" => Some(KeyCode::BrowserForward),
        "apprefresh" => Some(KeyCode::BrowserRefresh),
        "appbookmarks" => Some(KeyCode::BrowserFavorites),

        // Miscellaneous keys
        "pause" => Some(KeyCode::Pause),
        "escape" => Some(KeyCode::Escape),
        "help" => Some(KeyCode::Help),
        "printscreen" => Some(KeyCode::PrintScreen),
        "application" => Some(KeyCode::ContextMenu),
        "power" => Some(KeyCode::Power),
        "undo" => Some(KeyCode::Undo),

        _ => None,
    }
}
