//! Primes, and the just intonation subgroups they generate.

use std::fmt;
use std::str::FromStr;

use diophantine::Matrix;

use crate::Error;

/// Whether `n` is prime.
pub fn is_prime(n: u32) -> bool {
    if n < 2 {
        return false;
    }
    let mut p = 2u32;
    while p * p <= n {
        if n.is_multiple_of(p) {
            return false;
        }
        p += 1;
    }
    true
}

/// Returns all primes `p` with `2 <= p <= limit`, in increasing order.
fn primes_up_to(limit: u32) -> Vec<u32> {
    if limit < 2 {
        return vec![];
    }
    let n = limit as usize;
    let mut sieve = vec![true; n + 1];
    sieve[0] = false;
    sieve[1] = false;

    let mut i = 2;
    while i * i <= n {
        if sieve[i] {
            let mut j = i * i;
            while j <= n {
                sieve[j] = false;
                j += i;
            }
        }
        i += 1;
    }

    (2..=n).filter(|&i| sieve[i]).map(|i| i as u32).collect()
}

/// Factorizes `n` into prime powers, in increasing order of prime.
///
/// Returns an empty vector for `n == 1`.
fn prime_factors(mut n: u64) -> Vec<(u64, u32)> {
    debug_assert!(n != 0, "cannot factorize zero");
    let mut factors = Vec::new();
    let mut p = 2u64;
    while p * p <= n {
        if n.is_multiple_of(p) {
            let mut exp = 0;
            while n.is_multiple_of(p) {
                n /= p;
                exp += 1;
            }
            factors.push((p, exp));
        }
        p += 1;
    }
    if n > 1 {
        factors.push((n, 1));
    }
    factors
}

/// A just intonation subgroup: the multiplicative group of positive rationals
/// generated by a basis of distinct primes, written in increasing order.
///
/// The shorthand `2.3.7` denotes the subgroup generated by `{2, 3, 7}`, and is
/// both the [`Display`](fmt::Display) and the [`FromStr`] form of this type. A
/// full `p`-limit such as `2.3.5` is just the special case where the basis is
/// every prime up to `p`; see [`Subgroup::p_limit`].
///
/// Every basis must start with `2.3`. The notation system built on top of this
/// is a chain of pythagorean fifths, so the octave and the fifth must both be
/// available; subgroups such as `2.5.7` are not supported.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Subgroup {
    basis: Vec<u32>,
}

impl Subgroup {
    /// Builds a subgroup from a basis of primes.
    ///
    /// # Errors
    /// Returns an error if the basis does not start with `2.3`, is not
    /// strictly increasing, or contains a number that is not prime.
    pub fn new(basis: Vec<u32>) -> Result<Self, Error> {
        for &p in &basis {
            if !is_prime(p) {
                return Err(Error::InvalidSubgroup(format!("{p} is not prime")));
            }
        }
        if basis.windows(2).any(|w| w[1] <= w[0]) {
            return Err(Error::InvalidSubgroup(
                "basis must be strictly increasing".into(),
            ));
        }
        if basis.len() < 2 || basis[0] != 2 || basis[1] != 3 {
            return Err(Error::InvalidSubgroup(
                "basis must start with 2.3, since notation is built on a chain of fifths".into(),
            ));
        }
        Ok(Subgroup { basis })
    }

    /// The full `p`-limit subgroup, i.e. every prime up to `limit`.
    ///
    /// # Panics
    /// Panics if `limit < 3`, which would leave a basis without a fifth.
    pub fn p_limit(limit: u32) -> Self {
        Subgroup::new(primes_up_to(limit)).expect("primes up to a limit of at least 3 are a basis")
    }

    /// The generating primes, in increasing order.
    pub fn basis(&self) -> &[u32] {
        &self.basis
    }

    /// The dimension of the subgroup, i.e. the length of an interval vector over it.
    pub fn dim(&self) -> usize {
        self.basis.len()
    }

    /// Returns `log2(b)` for each basis element.
    pub fn log_primes(&self) -> Vec<f64> {
        self.basis.iter().map(|&p| f64::from(p).log2()).collect()
    }

    /// The size of `interval` in cents, i.e. `1200 * log2(prod(b_i ^ e_i))`.
    ///
    /// A negative result means the interval is descending (the rational it
    /// denotes is less than 1).
    ///
    /// # Panics
    /// Panics if `interval` does not have one entry per basis element.
    pub fn to_cents(&self, interval: &[i64]) -> f64 {
        assert_eq!(
            interval.len(),
            self.dim(),
            "interval must have one entry per basis element"
        );
        1200.0
            * interval
                .iter()
                .zip(&self.basis)
                .map(|(&e, &p)| e as f64 * f64::from(p).log2())
                .sum::<f64>()
    }

    /// `interval` if it is ascending and its inverse if it is descending, so
    /// that the result is never less than a unison.
    ///
    /// # Panics
    /// Panics if `interval` does not have one entry per basis element.
    pub fn ascending(&self, interval: &[i64]) -> Vec<i64> {
        if self.to_cents(interval) < 0.0 {
            interval.iter().map(|exponent| -exponent).collect()
        } else {
            interval.to_vec()
        }
    }

    /// The diagonal weight matrix on interval-vector coordinates, under
    /// `weighting`.
    pub fn weights(&self) -> Matrix<f64> {
        let n = self.dim();
        let mut w = vec![vec![0.0; n]; n];
        for (i, &p) in self.basis.iter().enumerate() {
            w[i][i] = f64::from(p).powi(2);
        }
        w
    }

    /// Factorizes the rational `num / den` into its interval vector over this
    /// basis. The fraction need not be in lowest terms.
    ///
    /// # Errors
    /// Returns [`Error::NotInSubgroup`] if any prime factor of `num` or `den`
    /// is not a basis element.
    ///
    /// # Panics
    /// Panics if `num` or `den` is zero.
    pub fn factorize(&self, num: u64, den: u64) -> Result<Vec<i64>, Error> {
        assert!(num != 0 && den != 0, "cannot factorize zero");
        let mut interval = vec![0i64; self.dim()];
        for (n, sign) in [(num, 1i64), (den, -1i64)] {
            for (p, exp) in prime_factors(n) {
                let index = u32::try_from(p)
                    .ok()
                    .and_then(|p| self.basis.iter().position(|&b| b == p))
                    .ok_or_else(|| {
                        Error::NotInSubgroup(format!(
                            "{num}/{den} has a factor of {p}, which is not in {self}"
                        ))
                    })?;
                interval[index] += sign * i64::from(exp);
            }
        }
        Ok(interval)
    }

    /// Parses a ratio such as `"81/80"`, or a whole number such as `"5"`, into
    /// its interval vector over this basis.
    ///
    /// # Errors
    /// Returns [`Error::InvalidRatio`] if `ratio` is not a fraction of two
    /// positive integers, and [`Error::NotInSubgroup`] if it has a prime factor
    /// outside the basis.
    pub fn parse_ratio(&self, ratio: &str) -> Result<Vec<i64>, Error> {
        let invalid = || Error::InvalidRatio(format!("{ratio:?} is not a ratio like `81/80`"));
        let (num, den) = ratio.trim().split_once('/').unwrap_or((ratio.trim(), "1"));
        let num: u64 = num.trim().parse().map_err(|_| invalid())?;
        let den: u64 = den.trim().parse().map_err(|_| invalid())?;
        if num == 0 || den == 0 {
            return Err(invalid());
        }
        self.factorize(num, den)
    }

    /// The rational `prod(b_i ^ e_i)` denoted by `interval`, as a fraction in
    /// lowest terms.
    ///
    /// # Errors
    /// Returns [`Error::Overflow`] if either side does not fit in a `u64`.
    ///
    /// # Panics
    /// Panics if `interval` does not have one entry per basis element.
    pub fn to_ratio(&self, interval: &[i64]) -> Result<(u64, u64), Error> {
        assert_eq!(
            interval.len(),
            self.dim(),
            "interval must have one entry per basis element"
        );
        // Positive exponents build the numerator, negative ones the denominator.
        // The basis is a set of distinct primes, so no common factor can arise
        // between the two sides and the result is already in lowest terms.
        let mut ratio = [1u64, 1u64];
        for (&e, &p) in interval.iter().zip(&self.basis) {
            let side = &mut ratio[usize::from(e < 0)];
            *side = u32::try_from(e.unsigned_abs())
                .ok()
                .and_then(|exp| u64::from(p).checked_pow(exp))
                .and_then(|factor| side.checked_mul(factor))
                .ok_or_else(|| {
                    Error::Overflow(format!("{p}^{e} does not fit in a 64 bit fraction"))
                })?;
        }
        Ok((ratio[0], ratio[1]))
    }
}

impl fmt::Display for Subgroup {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for (i, p) in self.basis.iter().enumerate() {
            if i > 0 {
                write!(f, ".")?;
            }
            write!(f, "{p}")?;
        }
        Ok(())
    }
}

impl FromStr for Subgroup {
    type Err = Error;

    /// Parses the shorthand form, e.g. `"2.3.7"`.
    fn from_str(s: &str) -> Result<Self, Error> {
        let basis = s
            .split('.')
            .map(|part| {
                part.trim()
                    .parse::<u32>()
                    .map_err(|_| Error::InvalidSubgroup(format!("{part:?} is not a number")))
            })
            .collect::<Result<Vec<u32>, Error>>()?;
        Subgroup::new(basis)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn primes_basic() {
        assert_eq!(primes_up_to(1), Vec::<u32>::new());
        assert_eq!(primes_up_to(2), vec![2]);
        assert_eq!(primes_up_to(5), vec![2, 3, 5]);
        assert_eq!(primes_up_to(11), vec![2, 3, 5, 7, 11]);
        assert!(!is_prime(1));
        assert!(is_prime(2));
        assert!(!is_prime(9));
        assert!(is_prime(97));
    }

    #[test]
    fn subgroup_shorthand() {
        let s: Subgroup = "2.3.7".parse().unwrap();
        assert_eq!(s.basis(), &[2, 3, 7]);
        assert_eq!(s.dim(), 3);
        assert_eq!(s.to_string(), "2.3.7");
        assert_eq!(Subgroup::p_limit(5).to_string(), "2.3.5");
        assert_eq!(Subgroup::p_limit(3).to_string(), "2.3");
        // A subgroup need not be a prime limit.
        assert_eq!("2.3.11.13".parse::<Subgroup>().unwrap().dim(), 4);
    }

    #[test]
    fn subgroup_rejects_bad_basis() {
        assert!(Subgroup::new(vec![]).is_err());
        // Not prime.
        assert!(Subgroup::new(vec![2, 3, 9]).is_err());
        // Repeated, and out of order.
        assert!(Subgroup::new(vec![2, 3, 3]).is_err());
        assert!(Subgroup::new(vec![3, 2]).is_err());
        assert!("2.3.x".parse::<Subgroup>().is_err());
        // Must start with 2.3: notation needs the octave and the fifth.
        assert!(Subgroup::new(vec![2]).is_err());
        assert!(Subgroup::new(vec![3, 5]).is_err());
        assert!("2.5.7".parse::<Subgroup>().is_err());
    }

    #[test]
    fn cents_basic() {
        let s = Subgroup::p_limit(5);
        // Unison.
        assert_eq!(s.to_cents(&[0, 0, 0]), 0.0);
        // Octave, 2/1.
        assert_eq!(s.to_cents(&[1, 0, 0]), 1200.0);
        // Two octaves down, 1/4.
        assert_eq!(s.to_cents(&[-2, 0, 0]), -2400.0);
        // Just fifth, 3/2.
        assert!((s.to_cents(&[-1, 1, 0]) - 701.955).abs() < 1e-3);
        // Syntonic comma, 81/80.
        assert!((s.to_cents(&[-4, 4, -1]) - 21.506).abs() < 1e-3);
        // 7/4 over 2.3.7, where the basis is not a prime limit.
        let s = Subgroup::new(vec![2, 3, 7]).unwrap();
        assert!((s.to_cents(&[-2, 0, 1]) - 968.826).abs() < 1e-3);
    }

    #[test]
    fn factorize_roundtrip() {
        let s = Subgroup::p_limit(5);
        assert_eq!(s.factorize(1, 1).unwrap(), vec![0, 0, 0]);
        assert_eq!(s.factorize(3, 2).unwrap(), vec![-1, 1, 0]);
        assert_eq!(s.factorize(81, 80).unwrap(), vec![-4, 4, -1]);
        // The fraction need not be in lowest terms.
        assert_eq!(s.factorize(6, 4).unwrap(), s.factorize(3, 2).unwrap());

        assert_eq!(s.to_ratio(&[0, 0, 0]).unwrap(), (1, 1));
        assert_eq!(s.to_ratio(&[-1, 1, 0]).unwrap(), (3, 2));
        assert_eq!(s.to_ratio(&[-4, 4, -1]).unwrap(), (81, 80));
        // 2^63 fits in a u64, 2^64 does not.
        assert!(s.to_ratio(&[63, 0, 0]).is_ok());
        assert!(s.to_ratio(&[64, 0, 0]).is_err());
    }

    #[test]
    fn parse_ratio() {
        let s = Subgroup::p_limit(5);
        assert_eq!(s.parse_ratio("81/80").unwrap(), vec![-4, 4, -1]);
        assert_eq!(s.parse_ratio(" 3 / 2 ").unwrap(), vec![-1, 1, 0]);
        assert_eq!(s.parse_ratio("5").unwrap(), vec![0, 0, 1]);
        for bad in ["", "3/", "/2", "0/1", "1/0", "-3/2", "3/2/1", "1.5"] {
            assert!(
                matches!(s.parse_ratio(bad), Err(Error::InvalidRatio(_))),
                "{bad:?}"
            );
        }
        assert!(matches!(s.parse_ratio("7/4"), Err(Error::NotInSubgroup(_))));
    }

    #[test]
    fn factorize_outside_subgroup() {
        let s = Subgroup::new(vec![2, 3, 7]).unwrap();
        // 5 is not a basis element of 2.3.7, in either numerator or denominator.
        assert!(s.factorize(5, 4).is_err());
        assert!(s.factorize(8, 5).is_err());
        assert!(s.factorize(7, 4).is_ok());
    }
}
