use winit::keyboard::KeyCode;

pub fn keycode_to_str(keycode: KeyCode) -> Option<&'static str> {
	match keycode {
		// Character keys (lowercase a-z)
		KeyCode::KeyA => Some("a"),
		KeyCode::KeyB => Some("b"),
		KeyCode::KeyC => Some("c"),
		KeyCode::KeyD => Some("d"),
		KeyCode::KeyE => Some("e"),
		KeyCode::KeyF => Some("f"),
		KeyCode::KeyG => Some("g"),
		KeyCode::KeyH => Some("h"),
		KeyCode::KeyI => Some("i"),
		KeyCode::KeyJ => Some("j"),
		KeyCode::KeyK => Some("k"),
		KeyCode::KeyL => Some("l"),
		KeyCode::KeyM => Some("m"),
		KeyCode::KeyN => Some("n"),
		KeyCode::KeyO => Some("o"),
		KeyCode::KeyP => Some("p"),
		KeyCode::KeyQ => Some("q"),
		KeyCode::KeyR => Some("r"),
		KeyCode::KeyS => Some("s"),
		KeyCode::KeyT => Some("t"),
		KeyCode::KeyU => Some("u"),
		KeyCode::KeyV => Some("v"),
		KeyCode::KeyW => Some("w"),
		KeyCode::KeyX => Some("x"),
		KeyCode::KeyY => Some("y"),
		KeyCode::KeyZ => Some("z"),

		// Number keys
		KeyCode::Digit0 => Some("0"),
		KeyCode::Digit1 => Some("1"),
		KeyCode::Digit2 => Some("2"),
		KeyCode::Digit3 => Some("3"),
		KeyCode::Digit4 => Some("4"),
		KeyCode::Digit5 => Some("5"),
		KeyCode::Digit6 => Some("6"),
		KeyCode::Digit7 => Some("7"),
		KeyCode::Digit8 => Some("8"),
		KeyCode::Digit9 => Some("9"),

		// Punctuation and symbols
		KeyCode::Space => Some("space"),
		KeyCode::Comma => Some(","),
		KeyCode::Minus => Some("-"),
		KeyCode::Period => Some("."),
		KeyCode::Slash => Some("/"),
		KeyCode::Semicolon => Some(";"),
		KeyCode::Equal => Some("="),
		KeyCode::BracketLeft => Some("["),
		KeyCode::Backslash => Some("\\"),
		KeyCode::BracketRight => Some("]"),
		KeyCode::Backquote => Some("`"),
		KeyCode::Quote => Some("'"),

		// Numpad keys
		KeyCode::Numpad0 => Some("kp0"),
		KeyCode::Numpad1 => Some("kp1"),
		KeyCode::Numpad2 => Some("kp2"),
		KeyCode::Numpad3 => Some("kp3"),
		KeyCode::Numpad4 => Some("kp4"),
		KeyCode::Numpad5 => Some("kp5"),
		KeyCode::Numpad6 => Some("kp6"),
		KeyCode::Numpad7 => Some("kp7"),
		KeyCode::Numpad8 => Some("kp8"),
		KeyCode::Numpad9 => Some("kp9"),
		KeyCode::NumpadDecimal => Some("kp."),
		KeyCode::NumpadComma => Some("kp,"),
		KeyCode::NumpadDivide => Some("kp/"),
		KeyCode::NumpadMultiply => Some("kp*"),
		KeyCode::NumpadSubtract => Some("kp-"),
		KeyCode::NumpadAdd => Some("kp+"),
		KeyCode::NumpadEnter => Some("kpenter"),
		KeyCode::NumpadEqual => Some("kp="),

		// Navigation keys
		KeyCode::ArrowUp => Some("up"),
		KeyCode::ArrowDown => Some("down"),
		KeyCode::ArrowRight => Some("right"),
		KeyCode::ArrowLeft => Some("left"),
		KeyCode::Home => Some("home"),
		KeyCode::End => Some("end"),
		KeyCode::PageUp => Some("pageup"),
		KeyCode::PageDown => Some("pagedown"),

		// Editing keys
		KeyCode::Insert => Some("insert"),
		KeyCode::Backspace => Some("backspace"),
		KeyCode::Tab => Some("tab"),
		KeyCode::NumpadClear => Some("clear"),
		KeyCode::Enter => Some("return"),
		KeyCode::Delete => Some("delete"),

		// Function keys
		KeyCode::F1 => Some("f1"),
		KeyCode::F2 => Some("f2"),
		KeyCode::F3 => Some("f3"),
		KeyCode::F4 => Some("f4"),
		KeyCode::F5 => Some("f5"),
		KeyCode::F6 => Some("f6"),
		KeyCode::F7 => Some("f7"),
		KeyCode::F8 => Some("f8"),
		KeyCode::F9 => Some("f9"),
		KeyCode::F10 => Some("f10"),
		KeyCode::F11 => Some("f11"),
		KeyCode::F12 => Some("f12"),
		KeyCode::F13 => Some("f13"),
		KeyCode::F14 => Some("f14"),
		KeyCode::F15 => Some("f15"),
		KeyCode::F16 => Some("f16"),
		KeyCode::F17 => Some("f17"),
		KeyCode::F18 => Some("f18"),

		// Modifier keys
		KeyCode::NumLock => Some("numlock"),
		KeyCode::CapsLock => Some("capslock"),
		KeyCode::ScrollLock => Some("scrolllock"),
		KeyCode::ShiftRight => Some("rshift"),
		KeyCode::ShiftLeft => Some("lshift"),
		KeyCode::ControlRight => Some("rctrl"),
		KeyCode::ControlLeft => Some("lctrl"),
		KeyCode::AltRight => Some("ralt"),
		KeyCode::AltLeft => Some("lalt"),
		KeyCode::SuperRight => Some("rgui"),
		KeyCode::SuperLeft => Some("lgui"),
		// KeyCode::Mode would be "mode" but it's not in included

		// Application keys
		KeyCode::BrowserSearch => Some("appsearch"),
		KeyCode::BrowserHome => Some("apphome"),
		KeyCode::BrowserBack => Some("appback"),
		KeyCode::BrowserForward => Some("appforward"),
		KeyCode::BrowserRefresh => Some("apprefresh"),
		KeyCode::BrowserFavorites => Some("appbookmarks"),

		// Miscellaneous keys
		KeyCode::Pause => Some("pause"),
		KeyCode::Escape => Some("escape"),
		KeyCode::Help => Some("help"),
		KeyCode::PrintScreen => Some("printscreen"),
		// KeyCode::SysReq would be "sysreq" but it's not in included
		KeyCode::ContextMenu => Some("application"),
		KeyCode::Power => Some("power"),
		KeyCode::Undo => Some("undo"),

		_ => None,
	}
}
